spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false

  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true